FROM mcr.microsoft.com/devcontainers/go:1.20

RUN sudo apt-get update && \
    sudo apt-get install --assume-yes --no-install-recommends python3-pip && \
    sudo pip3 install robotframework

EXPOSE 8080